services:
  
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: on-failure

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure

  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    restart: on-failure